
import Sidebar from "@/components/Sidebar";
import { AuthProvider } from "./Providers";
import "./globals.css";
import { RiStethoscopeLine } from "react-icons/ri";

export const metadata = {
  title: "Clinic Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
